DROP VIEW DISPONIVEIS;

CREATE VIEW disponiveis AS
	SELECT DISTINCT
		J.ID TITULO_ID,
	   	J.TITULO
	FROM JOGOS J
	INNER JOIN CONTAS C ON C.JOGO_ID = J.ID
	WHERE C.ID NOT IN (SELECT CONTA_ID FROM ALUGUEIS WHERE ATIVO =  'S'
		AND SITUACAO IN ('U', 'R') AND CAST(DATA_FIM AS DATE) >= CAST(NOW() AS DATE))
		AND C.ID NOT IN (SELECT CONTA_ID FROM SENHAS_EXPIRADAS)
	ORDER BY J.TITULO;